#!/usr/bin/env bash
set -e

export SOLC_FLAGS=${SOLC_FLAGS:-"--optimize"}
export ETH_FROM=$(seth rpc eth_coinbase)
export ETH_GAS=${ETH_GAS:-"4200000"}

dapp build

MEDIANIZER=$(dapp create Medianizer)
DSVALUE=$(dapp create DSValue)
DSCACHE=$(dapp create DSCache)
POKER=$(dapp create Poker)

#price=$(setzer price cryptocompare)
price="385.77999999999997"
wut=$(seth --to-uint256 $(seth --to-wei "$price" ETH))
zzz=$(date -d "+1 minutes" +%s)

#(set -x; setzer prod "$DSCACHE" "$wut" "$zzz")

#setzer peek $DSCACHE

seth send "$DSVALUE" "poke(bytes32)" "$wut"

seth send "$MEDIANIZER" "set(address)" "$DSVALUE"

setzer poke $MEDIANIZER

setzer read $MEDIANIZER

seth send $POKER "poke(address,address,bytes32)" $DSVALUE $MEDIANIZER $wut

cat > load-env << EOF
#!/bin/bash

export MEDIANIZER=$MEDIANIZER
export DSCACHE=$DSCACHE
export DSVALUE=$DSVALUE
export POKER=$POKER
EOF
